title: Xavier Data Research
description: AI Research
theme: just-the-docs

url: https://xavierdataresearch.com

aux_links:
  #Template Repository: https://github.com/just-the-docs/just-the-docs-template
