title: Xavier Data Research
description: AI Research
theme: just-the-docs

<!-- SCM Music Player https://www.scmplayer.net -->
<script type="text/javascript" src="https://www.scmplayer.net/script.js" 
data-config="{'skin':'skins/black/skin.css','volume':50,'autoplay':true,'shuffle':false,'repeat':1,'placement':'top','showplaylist':false,'playlist':[{'title':'Bjork - Its in our hands','url':'https://youtu.be/wv_4JnHvOTc'},{'title':'Aphex Twin - On ','url':'https://www.youtube.com/watch?v=38RMZ9H7Cg8'},{'title':'as long as ropes unravel fake rolex will travel','url':'https://www.youtube.com/watch?v=2FoVvS17nmg'},{'title':'Aphex Twin 4','url':'https://www.youtube.com/watch?v=7WAa3tY6cfo'},{'title':'oli xl - Go Oli Go!','url':'https://www.youtube.com/watch?v=Hj-Wq63iBZU'},{'title':'susumu yokota subconscious globe','url':'https://www.youtube.com/watch?v=4ze2tZx-9WE'}]}" ></script>
<!-- SCM Music Player script end -->


url: https://xavierdataresearch.com

aux_links:
  #Template Repository: https://github.com/just-the-docs/just-the-docs-template
